@extends('layout.index_pelanggan')
@section('content')
    @include('landing.sections.homes')
    @include('landing.sections.paket')
    @include('landing.sections.laundrycare')
    @include('landing.sections.tracking')
    @include('landing.sections.lokasi')
    @include('landing.sections.about')
@endsection
